[Greeter]

background=/etc/lightdm/background.jpg
draw-grid=true
show-clock=true
show-quit=true
theme-name=Dracula
icon-theme-name=Papirus
font-name=CaskaydiaMonoNerdFont-Light
enable-hidpi=off
clock-format=%H:%M
