;--------------------------------------------
; colors                                    ;
;--------------------------------------------

[colors]

	bar_bg = ${xrdb:background}
	bar_fg = ${xrdb:foreground}

	border_col = ${xrdb:background}

	modules_bg = ${xrdb:background}
	modules_fg = ${xrdb:foreground}

	mod_bg = ${xrdb:color7}

	modules_prefix_bg = ${xrdb:background}
	modules_prefix_fg = ${xrdb:foreground}

	urgent_bg  = ${xrdb:color1}
	focused_bg = ${xrdb:color10}

	essid_p_bg   = ${xrdb:color6}
	down_p_bg    = #5e606c
	cpu_p_bg     = ${xrdb:color5}
	ram_p_bg     = ${xrdb:color11}
	vol_p_bg     = #637b81
	bright_p_bg  = #c29f6f
	battery_p_bg = ${xrdb:color9}
	time_p_bg    = ${xrdb:color10}

;--------------------------------------------
; bars                                      ;
;--------------------------------------------

[bar/base]
	dpi      = 192
	width    = 100%
	height   = 32
	offset-x = 0
	offset-y = 0

	bottom = false

	foreground = ${xrdb:foreground}
	background = ${xrdb:background}

	border-bottom-size  = 0
	border-top-size     = 0

	border-left-size  = 0
	border-right-size = 0

	border-bottom-color = #000f0f0f
	border-top-color    = #000f0f0f

	border-left-color  = #000f0f0f
	border-right-color = #000f0f0f

	spacing            = 0
	padding-left       = 0
	padding-right      = 0
	module-margin-left = 0

	font-0 = CaskaydiaMonoNerdFont-Light:size=4;1

  modules-left   = workspaces
  modules-center = time xwindow
	modules-right  = volume paddinglite network date

	fixed-center = true

	monitor = ${env:MONITOR:}

[module/padding]
	type               = custom/text
	content            = "  "
	content-padding    = 1

[module/paddinglite]
	type               = custom/text
	content            = " "
	content-padding    = .5

[module/network]
	type          = internal/network
	interface     = wlan0
	ping-interval = 3
  format-connected = <ramp-signal><label-connected>
  format-disconnected = <label-disconnected>
  label-connected = %downspeed:9%
  ramp-signal-0 = 󰤯
  ramp-signal-1 = 󰤟
  ramp-signal-2 = 󰤢
  ramp-signal-3 = 󰤢
  ramp-signal-4 = 󰤨
  ramp-signal-5 = 󰤨

[module/date]
	type           = internal/date
	interval       = 1.0
	time           = "%Y-%m-%d 󰸘"
	label          = "%time%"
	format         = <label>
	format-padding = 0
	label-background = ${xrdb:background}
	label-foreground = ${xrdb:foreground}
	label-padding    = 4

[module/time]
	type           = internal/date
	interval       = 1.0
	time           = "  %H:%M"
	label          = "%time%"
	format         = <label>
	format-padding = 0
	label-background = ${xrdb:background}
	label-foreground = ${xrdb:foreground}
	label-padding    = 0

[module/workspaces]
	type            = internal/i3
	format          = <label-state><label-mode>
	index-sort      = true
	wrapping-scroll = false
	strip-wsnumbers = true
  label-active-font = 2

	label-mode-background    = ${xrdb:background}
	label-mode-foreground    = ${xrdb:foreground}
	label-mode-padding       = 1
	label-mode-padding-left  = 2
	label-mode-padding-right = 2

	label-focused               = %name%
	label-focused-background    = ${xrdb:color8}
  label-focused-foreground    = ${xrdb:color4}
	label-focused-padding       = 1
	label-focused-padding-left  = 2
	label-focused-padding-right = 2

	label-unfocused               = %name%
	label-unfocused-background    = ${xrdb:background}
	label-unfocused-foreground    = ${xrdb:foreground}
	label-unfocused-padding       = 1
	label-unfocused-padding-left  = 2
	label-unfocused-padding-right = 2

	label-visible               = %name%
	label-visible-background    = ${xrdb:background}
	label-visible-foreground    = ${xrdb:foreground}
	label-visible-padding       = 1
	label-visible-padding-left  = 2
	label-visible-padding-right = 2

	label-urgent               = •
	label-urgent-background    = ${xrdb:background}
	label-urgent-foreground    = ${xrdb:foreground}
	label-urgent-padding       = 1
	label-urgent-padding-left  = 2
	label-urgent-padding-right = 2

	pin-workspaces = true

[module/xwindow]
	y-offset      = 10
	type          = internal/xwindow
	format        = <label>
	label         = %title:0:50:%
	label-padding = 2

[module/volume]
	type          = internal/pulseaudio
	format-volume = <ramp-volume> <label-volume>

	mapped = true

	label-volume            = "%percentage%%"
	label-volume-background = ${xrdb:background}
	label-volume-foreground = ${xrdb:foreground}
	label-volume-padding    = 1

  ramp-volume-0 = 
  ramp-volume-1 = 
  ramp-volume-2 = 

	format-muted = <label-muted>
  click-right = pavucontrol

	label-muted            = "  %percentage%% (muted)"
	label-muted-background = ${xrdb:background}
	label-muted-foreground = ${xrdb:foregroung}
	label-muted-padding    = 1

	format-volume-padding = 0
	format-muted-padding  = 0

[module/music]
	type = internal/mpd

	host = 127.0.0.1
	port = 6600

	interval = 2

	format-online = <icon-prev> <icon-seekb> <icon-stop> <toggle> <icon-seekf> <icon-next>  <icon-repeat> <icon-random>  <bar-progress> <label-time>  <label-song>

	label-song         = "%artist% - %title% "
	label-song-padding = 0
	label-song-background = ${xrdb:background}
	label-song-foreground = ${xrdb:foreground}

  label-time = %elapsed% / %total%
icon-play = ⏵
icon-pause = ⏸
icon-stop = ⏹
icon-prev = ⏮
icon-next = ⏭
icon-seekb = ⏪
icon-seekf = ⏩
icon-random = 🔀
icon-repeat = 🔁
icon-repeatone = 🔂
icon-single = 🔂
icon-consume = ✀

	format-online-prefix-padding = 0





[module/cpu]
	type             = internal/cpu
	interval         = 0.5
	format           = <label>
	label            = %percentage%%
	label-background = ${colors.modules_bg}
	label-foreground = ${colors.modules_fg}
	label-padding    = 1

	format-prefix = 

	format-prefix-padding    = 1
	format-prefix-background = ${colors.cpu_p_bg}
	format-prefix-foreground = ${colors.modules_prefix_fg}

[module/ram]
	type     = internal/memory
	interval = 3

	format           = <label>
	label            = "%percentage_used%%"
	label-background = ${colors.modules_bg}
	label-foreground = ${colors.modules_fg}
	label-padding    = 1

	format-prefix = 

	format-prefix-padding    = 1
	format-prefix-background = ${colors.ram_p_bg}
	format-prefix-foreground = ${colors.modules_prefix_fg}


[module/essid]
	inherit = module/network

	format-connected = <label-connected>

	format-connected-prefix              = ""
	format-connected-prefix-padding      = 1
	format-connected-prefix-padding-left = 1
	format-connected-prefix-background   = ${xrdb:background}
	format-connected-prefix-foreground   = ${xrdb:color5}

	label-connected               = "%essid%"
	label-connected-background    = ${xrdb:background}
	label-connected-foreground    = ${xrdb:foreground}
	label-connected-padding       = 1
	label-connected-padding-right = 1

	ramp-signal-background    = ${xrdb:background}
	ramp-signal-foreground    = ${xrdb:foreground}
	ramp-connected-foreground = ${xrdb:foreground}
	ramp-signal-padding       = 1

	format-disconnected = <label-disconnected>

	format-disconnected-prefix              = ""
	format-disconnected-prefix-padding      = 1
	format-disconnected-prefix-padding-left = 1
	format-disconnected-prefix-background   = ${xrdb:background}
	format-disconnected-prefix-foreground   = ${xrdb:foreground}

	label-disconnected               = "DISCONNECTED"
	label-disconnected-background    = ${xrdb:background}
	label-disconnected-foreground    = ${xrdb:foreground}
	label-disconnected-padding       = 1
	label-disconnected-padding-right = 1


[module/down]
	inherit = module/network

	format-connected = <label-connected>

	format-connected-prefix            = 
	format-connected-prefix-background = ${colors.down_p_bg}
	format-connected-prefix-foreground = ${colors.modules_prefix_fg}
	format-connected-prefix-padding    = 1

	label-connected               = %{T2}%downspeed:7%%{T-}
	label-connected-background    = ${colors.modules_bg}
	label-connected-foreground    = ${colors.modules_fg}
	label-connected-padding-right = 1



[module/openbox]
	type                      = internal/xworkspaces
	pin-workspaces            = true
	enable-click              = false
	enable-scroll             = false
	format                    = <label-state>
	label-monitor             = %name%
	label-active              = %icon%%name%
	label-active-foreground   = ${colors.obfg}
	label-active-background   = ${colors.obbg}
	label-active-underline    = #fba922
	label-active-padding      = 1
	label-occupied            = %name%
	label-occupied-background = ${colors.obbg}
	label-occupied-padding    = 1
	label-urgent              = %index%
	label-urgent-foreground   = #000000
	label-urgent-background   = #bd2c40
	label-urgent-underline    = #9b0a20
	label-empty               = %name%
	label-empty-padding       = 1
	label-empty-background    = ${colors.obibg}
	label-empty-foreground    = ${colors.obifg}

