#:schema https://jj-vcs.github.io/jj/latest/config-schema.json

[ui]
default-command = "log"
editor = "nvim"

[user]
name = "Luiz Strobelt"
email = "luiz.strobelt@gmail.com"

[aliases]
spr = ["util", "exec", "--", "jj-spr"]
